export const mockData = [
  {
    antojo: false,
    hora: "07:30",
    etiqueta: "☕️ Desayuno",
    duracion: "0",
    intensidad: "0",
    comida:"🍞 Tostada con aguacate",
  },
  {
    antojo: true,
    hora: "10:00",
    etiqueta: "🍫 Snack",
    duracion: "5",
    intensidad: "3",
    comida: "🍫 Chocolate negro",
  },
  {
    antojo: false,
    hora: "12:30",
    etiqueta: "🍴 Almuerzo",
    duracion: "30",
    intensidad: "0",
    comida: "🍲 Sopa de lentejas",
  },
  {
    antojo: false,
    hora: "15:00",
    etiqueta: "🍏 Merienda",
    duracion: "0",
    intensidad: "0",
    comida: "🍎 Manzana",
  },
  {
    antojo: true,
    hora: "16:15",
    etiqueta: "🍟 Snack",
    duracion: "10",
    intensidad: "2",
    comida: "🍟 Papas fritas",
  },
  {
    antojo: false,
    hora: "19:00",
    etiqueta: "🍴 Cena",
    duracion: "0",
    intensidad: "0",
    comida: "🥗 Ensalada mixta",
  },
  {
    antojo: false,
    hora: "08:15",
    etiqueta: "☕️ Desayuno",
    duracion: "10",
    intensidad: "1",
    comida: "🥣 Avena con frutas",
  },
  {
    antojo: true,
    hora: "11:45",
    etiqueta: "🍰 Snack",
    duracion: "5",
    intensidad: "4",
    comida: "🍰 Pastel de chocolate",
  },
  {
    antojo: false,
    hora: "13:00",
    etiqueta: "🍴 Almuerzo",
    duracion: "25",
    intensidad: "0",
    comida: "🍚 Arroz con pollo",
  },
  {
    antojo: false,
    hora: "14:30",
    etiqueta: "🍏 Merienda",
    duracion: "0",
    intensidad: "0",
    comida: "🍌 Plátano",
  },
  {
    antojo: true,
    hora: "17:00",
    etiqueta: "🍫 Snack",
    duracion: "5",
    intensidad: "3",
    comida: "🍿 Palomitas de maíz",
  },
  {
    antojo: false,
    hora: "20:00",
    etiqueta: "🍴 Cena",
    duracion: "0",
    intensidad: "0",
    comida: "🍝 Pasta con verduras",
  },
  {
    antojo: false,
    hora: "09:00",
    etiqueta: "☕️ Desayuno",
    duracion: "0",
    intensidad: "0",
    comida: "🍳 Huevos revueltos",
  },
  {
    antojo: true,
    hora: "10:45",
    etiqueta: "🍪 Snack",
    duracion: "5",
    intensidad: "2",
    comida: "🍪 Galletas integrales",
  },
  {
    antojo: false,
    hora: "13:30",
    etiqueta: "🍴 Almuerzo",
    duracion: "20",
    intensidad: "0",
    comida: "🥘 Paella de verduras",
  },
  {
    antojo: false,
    hora: "16:00",
    etiqueta: "🍏 Merienda",
    duracion: "0",
    intensidad: "0",
    comida: "🍇 Uvas",
  },
  {
    antojo: true,
    hora: "18:30",
    etiqueta: "🍧 Snack",
    duracion: "5",
    intensidad: "3",
    comida: "🍧 Helado de vainilla",
  },
  {
    antojo: false,
    hora: "21:00",
    etiqueta: "🍴 Cena",
    duracion: "0",
    intensidad: "0",
    comida: "🍲 Guiso de garbanzos",
  },
  {
    antojo: false,
    hora: "08:00",
    etiqueta: "☕️ Desayuno",
    duracion: "0",
    intensidad: "0",
    comida: "🥑 Pan con aguacate",
  },
  {
    antojo: true,
    hora: "15:15",
    etiqueta: "🍫 Snack",
    duracion: "10",
    intensidad: "4",
    comida: "🍰 Brownie de chocolate",
  },
];
